name: Deploy Container
on: 
  push:
    branches:
      - main
defaults:
  run: 
    working-directory: package/container
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'